### ISSUE TITLE
Create Header and Home Sections

### ISSUE THREAD

**Issue by sarah-abu-zeineh** [gsg-K1-FC/Project0-Hamzah-Sarah-Bara#3]
### - Working on : 

Header and Home sections.

 This is how is gonna be .

![header](https://user-images.githubusercontent.com/70340194/95630986-826f5b80-0a8b-11eb-9504-de2402c15a72.png)

 **The structure is gonna be as follows :**
2 files -> _index.html style.css_

**Responsive Design :**

- Approach :
      mobile first.
- Breakpoints Details :
     `min-width: 780px 
      min-width: 1000px `

**Colors to use :** 
- `rgba(55, 64, 85, 0.9)` for Header background.
- `white` for  text inside Header && Home Sections.
- `yellow` for Git Started in Home Section [Border and after hover] && for text inside Header after hover.

**Font Family :**
- `"Open Sans", sans-serif` -> for text in Header
- `"Raleway", sans-serif`-> for the text in the Home Section.

**Comment by hamzah-bahar** [comment]
![image](https://user-images.githubusercontent.com/47035954/95648210-284bb600-0ade-11eb-887c-1775ee402ad0.png)
I think this is a different section and not part of the header

**Comment by sarah-abu-zeineh** [comment]
> ![image](https://user-images.githubusercontent.com/47035954/95648210-284bb600-0ade-11eb-887c-1775ee402ad0.png)
> I think this is a different section and not part of the header

yah I know , but I think it was  a part of Home Section !? if its not I'm not going to work on it .
