### ISSUE TITLE
Reference Section

### ISSUE THREAD

**Issue by hamzah-bahar** [gsg-K1-FC/Project0-Hamzah-Sarah-Bara#7]
### Working on: 

- Reference Section 

![image](https://user-images.githubusercontent.com/47035954/95676138-b9955800-0bc4-11eb-86c3-0e0bd2c9f63d.png)

- Will be done soon (Hopefully)

**Comment by saraAAZ** [comment]
All the best, partner.✨

**Comment by sarah-abu-zeineh** [comment]
go ahead ✨✨
